### PR TITLE
Add Set, Gauge and Decrement API. Update token control

### PR DESCRIPTION
**Pull request by pihomeserver**
I had errors with MD5 comparison where mine was in upper case and the calculated one in lower case

### CODE REVIEW

**Comment by kennydee** [comment]
Related to #9 
Seems there is an issue with the test now ? 
Is the test suite pass on your computer (i think all instructions for it are in the readme :))

Anyway, thanks for contributing :)

**Comment by pihomeserver** [comment]
Oops sorry ! I updated the security tests by updating expected tokens (i switched lowercase char to uppercase)
Hope this one is correct

**Comment by kennydee** [comment]
Yes this is better, but i think, the good way to do it, is to have both (uppercase and lowercase) test.
This is a way to confirm, previous test always work, and new one with uppercase too.
:)

**Comment by pihomeserver** [comment]
Update of the pull request to include 3 new API entries. Do not know how to do 2 separate requests if it's possible

**Comment by omansour** [comment]
v0.3

**Pull request merged**
